layout_spectrum: 1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d09b9f56-57a7-4ed1-870c-09a9a01a2137.ai
author:
  name: Ginger Buchanan
  email: gingerb421@gmail.com
name: GBGRAPHICS
title: For Art of All Kinds
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6446809
color:
  brandStrength: 0.7426529573276639
  lightness: 0.09557373
  saturation: 0.2556272
  rhythmicContrast: 0.8765957
  brandColors:
    - '#302E38'
    - '#BDA289'
    - '#907D5C'
    - '#70593D'
    - '#ECCAAA'
